### ISSUE TITLE
RabbitMQ: Shared Library (Python)

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/broker-lib-py#1]
This repo will be used as a shared library across the different system components. It aims to standardise the way we broker messages between services.

### Tasks

- [x] Should have a enum Status
- [ ] Should have an interface Workflow
- [x] Should have an interface Queue
- [x] Should have a set of predefined Queues
- [x] Should have a set of predefined Workflows
- [x] Should have a connect function
- [x] Should have a publish function
- [x] Should have a consume function

#### Status

```ts
enum Status {
  PENDING,
  IN_PROGRESS,
  SUCCESS,
  FAILED,
}
```

#### Interfaces

```ts
interface Workflow {
  uuid?: string
  name: string
  status: Status
  data: any
  sequence: Queue[]
}

interface Queue {
  name: string
  description: string
  status: Status
  message: any
  start: Date
  end: Date
  runtime: number
  error: Error
}
```

#### Predefined Queues

```ts
interface Queues {
  [key: string]: Queue
}

const queues: Queues = {
  "discord.fetch": { ... }
}
```

#### Predefined Workflows

```ts
interface Workflows {
  [key: string]: Workflow
}

const workflows: Workflows = {
  "discord.analysis": { ... }
}
```

Pseudo-code.

## Predefined Queues:

```ts
const queues = {
  discord: {
    fetch: {
      name: "discord.fetch",
      description: "Fetch and persist raw discord data",
      status: Status.PENDING,
    },
    heatmap: {
      run: {
        name: "discord.heatmap",
        description: "Generate a discord heatmap and member activities",
        status: Status.PENDING,
      },
      persist: {
        name: "discord.heatmap.persist",
        description: "Persist discord heatmap and member activities",
        status: Status.PENDING,
      },
    },
    completed: {
      name: "discord.completed",
      description: "Completed the discord analysis",
      status: Status.PENDING,
    }
  }
}
```

## Predefined Workflows:

```ts
const workflows = {
  discord: {
    analysis: {
      name: "discord.analysis",
      description: "Fetches the latest discord data, analyses it, and produces heatmaps.",
      status: Status.PENDING,
      sequence: [
        queues.discord.fetch,
        queues.discord.heatmap,
        queues.discord.heatmap.persist,
        queues.discord.completed
      ]
    }
  }
}
```

These should be stored statically. Then we can call:
```ts
const wf = mb.createWorkflow(workflows.discord.analysis, data)
```

I would expect `wf` to return an instance of a workflow based on the above. i.e.

```ts
function createWorkflow(wf, data) {
  wf.uuid = generate_uuid()
  wf.data = data
  return wf
}
```

#### Functions
```ts
// system component 1
const mb = new MessageBroker(connection_args)
const wf = mb.createWorkflow(workflows.discord.analysis)
mb.publish(queue.sequence[0].name, data)

// system component 2
const mb = new MessageBroker(connection_args)
mb.consume(queues.discord.fetch, () => { /* do something */ })
```

### Documentation
- https://medium.com/duda/shared-libraries-design-and-best-practices-710774ae0bdc
- https://pinnate-bobcat-fe2.notion.site/RabbitMQ-eb45a38abb094601b392daf592eb09b3
- https://github.com/RnDAO/tc-dbComm
- https://github.com/RnDAO/tc-messageBroker

**NOTE: PLEASE CONNECT WITH @scientiststwin TO ALIGN + DOCUMENT EXACT SPECIFICATIONS**

**Comment by amindadgar** [comment]
Implementing the pre-defined Queues in Python. https://github.com/RnDAO/tc-messageBroker/issues/1#issuecomment-1539949718

Should it be a dictionary of dictionaries? More specifically A dictionary of Events dictionary? (the pseudo-code below)
```
dict[ queue_item: str , dict[event_name: str, Event]]
```

@cyri113

**Comment by amindadgar** [comment]
For now, based on the type-script project our events and queues have been set up with static string values.

**Comment by amindadgar** [comment]
To test the project we have to set-up rabbitMQ on GitHub action and then we could write more test functions. Now, working on testing the project further.
