### ISSUE TITLE
Add CC_TEST_REPORTER_ID to Github repository secret

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/broker-lib-py#3]
In order to report the test results to CodeClimate, we need to provide a key `CC_TEST_REPORTER_ID`.

## Task

- [x] Go to https://codeclimate.com/github/RnDAO/tc-messageBrokerPython
- [x] Go to the **Repo Settings**
- [x] Go to **Test coverage**
- [x] Copy the `TEST REPORTER ID`
- [x] Go to https://github.com/RnDAO/tc-messageBrokerPython/settings/secrets/actions
- [x] Click on **New repository secret**
- [x] Enter the name (`CC_TEST_REPORTER_ID`) and paste the TEST REPORTER ID in the Secret.
- [x] Click on **Add secret**
