### ISSUE TITLE
Add twitter predefined terms

### ISSUE THREAD

**Issue by amindadgar** [TogetherCrew/broker-lib-py#30]
Based on the web3 foundation we have to work on the twitter platform. For the new platform we have new predefined terms which we should add to our codes. Based on the created issue https://github.com/TogetherCrew/operations/issues/56 we have to implement the tasks below

```[tasklist]
### Tasks
- [ ] Add `TWITTER_REFRESH` choreography
- [ ] Add `Queue.TWITTER_BOT` queue
- [ ] Add `Queue.TWITTER_ANALYZER` queue
- [ ] Add `Event.TWITTER_BOT.EXTRACT` event
- [ ] Add `Event.TWITTER_BOT.SEND_MESSAGE` event
- [ ] Add `Event.TWITTER_ANALYZER.RUN` event
```
